name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Python (adjust the version as needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          mkdir package
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./package

      # Step 4: Copy Lambda function code into the package folder
      - name: Add Lambda function code
        run: cp -r src ./package/

      # Step 5: Zip the contents of the package folder
      - name: Create Zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .  # Zip everything in the package folder and move it to the root of the zip file

      # Step 6: Deploy to AWS Lambda
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:756316131141:function:store-user-spotify-data \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
